using System;
using System.Collections.Generic;
using System.Linq;
using TacticsGame.Core;
using UnityEngine;

namespace TacticsGame.Data.TacticsRuleset
{
    /// <summary>
    /// A core service that holds a compiled reference to every TacticsRuleset item in the game.
    /// Used for fast O(1) lookups and AI queries during runtime.
    /// Resolves cross-references like "What spells does this feat grant?"
    /// </summary>
    public class CompendiumRegistry : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("The master database asset generated by the Unity Importer.")]
        private TacticsRulesetDatabase masterDatabase;

        public TacticsRulesetDatabase MasterDatabase => masterDatabase;
        private Dictionary<string, GameElementSO> allElements =
            new Dictionary<string, GameElementSO>();
        private Dictionary<string, SpellSO> spells = new Dictionary<string, SpellSO>();
        private Dictionary<string, FeatSO> feats = new Dictionary<string, FeatSO>();

        public bool IsInitialized { get; private set; } = false;

        private void Awake()
        {
            ServiceLocator.Register(this);

            if (masterDatabase != null)
            {
                Initialize(masterDatabase);
            }
            else
            {
                Debug.LogWarning(
                    "[CompendiumRegistry] No Master Database assigned. Data will be missing!"
                );
            }
        }

        private void OnDestroy()
        {
            ServiceLocator.Unregister<CompendiumRegistry>();
        }

        public void Initialize(TacticsRulesetDatabase database)
        {
            masterDatabase = database;
            allElements.Clear();
            spells.Clear();
            feats.Clear();

            // Index Spells
            foreach (var spell in database.AllSpells)
            {
                if (spell == null || string.IsNullOrEmpty(spell.Id))
                    continue;
                spells[spell.Id] = spell;
                allElements[spell.Id] = spell;
            }

            // Index Feats
            foreach (var feat in database.AllFeats)
            {
                if (feat == null || string.IsNullOrEmpty(feat.Id))
                    continue;
                feats[feat.Id] = feat;
                allElements[feat.Id] = feat;
            }

            // Index Generic Items
            foreach (var item in database.AllItems)
            {
                if (item == null || string.IsNullOrEmpty(item.Id))
                    continue;
                allElements[item.Id] = item;
            }

            IsInitialized = true;
            Debug.Log(
                $"[CompendiumRegistry] Initialized with {spells.Count} Spells, {feats.Count} Feats, and {allElements.Count} Total Items."
            );
        }

        // Fast Lookups

        public SpellSO GetSpell(string id)
        {
            return spells.TryGetValue(id, out var spell) ? spell : null;
        }

        public FeatSO GetFeat(string id)
        {
            return feats.TryGetValue(id, out var feat) ? feat : null;
        }

        public GameElementSO GetElement(string id)
        {
            return allElements.TryGetValue(id, out var element) ? element : null;
        }

        // Relational Queries

        /// <summary>
        /// Reads an element's `GrantedItemIds` array and returns all corresponding SpellSOs.
        /// </summary>
        public List<SpellSO> ResolveGrantedSpells(GameElementSO element)
        {
            if (element == null)
                return new List<SpellSO>();

            return element
                .GrantedItemIds.Select(id => GetSpell(id))
                .Where(spell => spell != null)
                .ToList();
        }

        /// <summary>
        /// Gets all spells matching the given traits. Useful for UI filtering or AI.
        /// </summary>
        public List<SpellSO> GetSpellsByTraits(params string[] traits)
        {
            return spells.Values.Where(s => traits.All(t => s.Traits.Contains(t))).ToList();
        }

        // Add additional queries here as needed (e.g. GetSpellsWithAITag("heal"))
    }
}
